"
Solo tiene su contenido y la respuesta a la que pertenece.
Eliminar la respuesta debe de eliminarla de la lista del usuario.
"
Class {
	#name : #Respuesta,
	#superclass : #Post,
	#instVars : [
		'contenido',
		'preguntaOriginal'
	],
	#category : #'test-github-Model'
}

{ #category : #cleanup }
Respuesta >> eliminarRespuesta [
	"No estoy seguro de como implementar esto"
	"scope: class-variables  &  instance-variables"	
			
	
]
